---
- hosts: all
  become: yes
  tasks:
    - name: Ensure required kernel modules are loaded
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay
      tags: setup

    - name: Load kernel modules immediately
      command: modprobe {{ item }}
      loop:
        - br_netfilter
        - overlay
      tags: setup

    - name: Configure sysctl parameters
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
      tags: setup

    - name: Apply sysctl parameters
      command: sysctl --system
      tags: setup

    - name: Disable swap immediately
      command: swapoff -a
      tags: setup

    - name: Permanently disable swap in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \1'
      tags: setup