# postgres-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gitlab
type: Opaque
stringData:
  username: gitlab
  password: +BP52QIxpT/flVCMpL3KXA==
  database: gitlab_production