apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  namespace: gitlab
spec:
  type: NodePort
  ports:
  - port: 5540
    targetPort: 5540
    nodePort: 30081
  selector:
    app: redisinsight