apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redis/redisinsight:latest  # Known stable version
        ports:
        - containerPort: 5540
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /db
      volumes:
      - name: data
        emptyDir: {}