apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-ebs-sc  # Same storage class
  resources:
    requests:
      storage: 5Gi