apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  iops: "3000"  # Recommended minimum for PostgreSQL
  throughput: "125"  # MB/s
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values: [eu-west-1a]